#!/usr/bin/perl

use strict;
use Getopt::Std;
use Net::MessageBus;
use Data::Dumper;
use MIME::Base64;
use YAML::Tiny;

my %opt;
getopts ('bc:d:o:', \%opt);

my $config = YAML::Tiny->read($opt{c} or $ENV{HOME}."/.config/netdrop") or die "No config.";
my $sender = $config->[0]->{client}->{sender};
if (!$sender) { $sender = $ENV{USER}.'@'.`hostname`; }
chomp($sender);

$opt{o} or $opt{o} = $config->[0]->{client}->{"output-file"};
my $MessageBus = Net::MessageBus->new(
  server => $config->[0]->{client}->{server},
  port => $config->[0]->{client}->{port},
  group => 'NetBoard',
  sender => $sender,
  username => $config->[0]->{client}->{username},
  password=>$config->[0]->{client}->{password},
);

$MessageBus->subscribe_all;

while (my $message = $MessageBus->next_message()) {
  if ($message->sender() ne $sender) {  
    my $payload = decode_base64($message->payload()->{'message'});
    if ($opt{b}) { print "\007"; }
    print $message->sender()." sent ".$message->type().":\n";
    print $payload;
    chomp($payload);
    if ($opt{o}) {
      open(MYFILE, '>'.$opt{o});
    } else {
      $opt{d} = "" unless $opt{d};
      open(MYFILE, '>'.$opt{d}.'/'.$message->sender());
    }

    print MYFILE $payload;
    close (MYFILE);
  }
}

